//..............................
// UI Lab Inc. Arthur Amshukov .
//..............................
namespace UILab.Art.Arcturus.Ir.Instructions;

public record Phi<TSymbol>(Argument<TSymbol> Symbol);
