//..............................
// UI Lab Inc. Arthur Amshukov .
//..............................
namespace UILab.Art.Framework.Adt.Graph;

/// <summary>
/// A singleton edge in a directed hypergraph involves exactly one vertex in either the source set, target set, or both.
/// Some comments are generated by ChatGPT.
/// </summary>
public enum SingletonEdgeType
{
    /// <summary>
    /// A hyperedge where one vertex is both the source and target.
    /// It is denoted as 𝑒 = ({𝑣},{𝑣}), meaning the vertex 𝑣 is both the source and the target.
    /// </summary>
    SelfLoop = 1,

    /// <summary>
    /// A hyperedge with one source vertex and potentially multiple targets.
    /// Denoted as 𝑒 = ({𝑣},𝑇), where 𝑇 is a set of vertices, and 𝑣 is the only source.
    /// </summary>
    SourceOnly = 2,

    /// <summary>
    /// A hyperedge with one target vertex and potentially multiple sources.
    /// Denoted as 𝑒 = (𝑆,{𝑣}), where 𝑆 is a set of source vertices, and 𝑣 is the only target.
    /// </summary>
    TargetOnly = 3
}
