//..............................
// UI Lab Inc. Arthur Amshukov .
//..............................
namespace UILab.Art.Framework.Adt.Graph;

/// <summary>
/// A k-uniform directed hypergraph is one where all hyperedges have exactly k vertices in either the source set, target set, or both.
/// Some comments are generated by ChatGPT.
/// </summary>
public enum UniformType
{
    /// <summary>
    /// Source-set k-uniform: Each hyperedge has exactly k vertices in its source set.
    /// This means that for every hyperedge 𝑒 = (𝑆,𝑇), the size of the source set ∣𝑆∣ is equal to k.
    /// </summary>
    SourceSet = 1,

    /// <summary>
    /// Target-set k-uniform: Each hyperedge has exactly k vertices in its target set.
    /// For every hyperedge 𝑒 = (𝑆,𝑇), the size of the target set ∣𝑇∣ is equal to k.
    /// </summary>
    TargetSet = 2,

    /// <summary>
    /// Fully k-uniform: Each hyperedge has exactly k vertices in both the source and target sets.
    /// For every hyperedge 𝑒 = (𝑆,𝑇), both ∣𝑆∣ = 𝑘 and ∣𝑇∣ = 𝑘.
    /// </summary>
    Full = 3
}
