//..............................
// UI Lab Inc. Arthur Amshukov .
//..............................
namespace UILab.Art.Framework.Adt.Graph;

public delegate void VertexEventHandler<TVertex>(TVertex vertex);
